### ISSUE TITLE
"ValueError: operands could not be broadcast together with shapes" in IMM.py

### ISSUE THREAD

**Issue by Prokhozhijj** [rlabbe/filterpy#141]
Please, consider following example:

```
# 3d party
from filterpy.kalman import IMMEstimator
from filterpy.common import kinematic_kf
import numpy as np

def get_data():
    return np.random.uniform(0, 2, 100)

data = get_data()

dim_x1 = 2
dim_x2 = 3
dt = 10

f1 = kinematic_kf(1, dim_x1 - 1, dt = dt)
f2 = kinematic_kf(1, dim_x2 - 1, dt = dt)

filters = (f1, f2)
mu = (0.5, 0.5)
trans = np.array([[0.5, 0.5], [0.5, 0.5]])
bank = IMMEstimator(filters, mu, trans)

n = len(data)
results = np.zeros(n)
for i in range(n):
    bank.update(data[i])
    results[i] = bank.x[0]

```

And I am getting:

```
Traceback (most recent call last):
  File "test_IMM.py", line 26, in <module>
    bank.update(data[i])
  File "g:\proj\python\filterpy\filterpy\kalman\IMM.py", line 135, in update
    x += kf.x * wj
ValueError: operands could not be broadcast together with shapes (2,1) (3,1) (2,1)
```

**Comment by rlabbe** [comment]
This is not a FilterPy bug. All of the filters must have the same state dimension. If you think about it, you'll see why. The IMM is blending the states of all of the filters in the filter bank; if they were of different shapes or had different interpretations (x[2] is acceleration in one, but a coefficient of friction in another), then there is no way to blend the states together to get an estimate.

I was going to point you to the book, but looked and realized that I didn't cover this. So I will leave this open for the time being while I fix the book. Actually, today I was planning on writing a FilterPy tutorial, so it will also go there.

**Comment by Prokhozhijj** [comment]
Thanks.

**Comment by rlabbe** [comment]
I added a check for all the filters to have the same state dimension and just pushed it to master.

**Comment by Prokhozhijj** [comment]
> You seem to be doing a constant velocity and constant acceleration filter. for that I'd encode both with a state dimension of 3, but for constant velocity just implement F so that no acceleration is taken into account. But, to be honest, I don't think the IMM does so well with that sort of thing. 

I've just checked your proposition. It seems you are right. IMM assigns larger weights for quick filters (with acceleration)  so slow filters (without acceleration) are almost ignored.
