### ISSUE TITLE
AttributeError: 'int' object has no attribute 'T'

### ISSUE THREAD

**Issue by alexblack** [rlabbe/filterpy#41]
I'm trying to get started implementing a Kalman Filter using filterpy, using code from the readme:

```
kf = KalmanFilter(dim_x=2, dim_z=1)
kf.x = np.array([[x],[0.]])       # initial state (location and velocity)
kf.F = np.array([[1.,1.], [0.,1.]])    # state transition matrix
kf.H = np.array([[1.,0.]])    # Measurement function
kf.P *= 1000.                 # covariance matrix
kf.R = 5                      # state uncertainty
kf.Q = Q_discrete_white_noise(2, dt, .1) # process uncertainty
```

Then later
```
kf.predict()
kf.update(x)
```

Then I get this error when invoking `predict`:

```
Traceback (most recent call last):
  File "drone/test_predict.py", line 102, in <module>
    main()
  File "drone/test_predict.py", line 73, in main
    kf.predict()
  File "/Users/alex/.virtualenvs/ddc/lib/python2.7/site-packages/filterpy/kalman/kalman_filter.py", line 416, in predict
    self._P = self._alpha_sq * dot3(F, self._P, F.T) + Q
AttributeError: 'int' object has no attribute 'T'
```

**Comment by alexblack** [comment]
My mistake, no issue.

**Comment by mayankgupta1905** [comment]
what was your mistake? Cause I might be making the same mistake

**Comment by psvnagasai** [comment]
yep, i made the same mistake.
